-- Create services table
CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    fee TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Active', 'Draft', 'Suspended')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create applications table
CREATE TABLE public.applications (
    id TEXT PRIMARY KEY,
    applicant TEXT NOT NULL,
    applicant_id TEXT NOT NULL,
    applicant_email TEXT NOT NULL,
    applicant_phone TEXT NOT NULL,
    service TEXT NOT NULL,
    date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Pending Review', 'Approved', 'Rejected', 'Changes Requested')),
    amount NUMERIC NOT NULL,
    business_name TEXT,
    ward TEXT,
    sub_county TEXT,
    address TEXT,
    type TEXT NOT NULL CHECK (type IN ('citizen', 'business')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) -- to link to authenticated user
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- Services Policies
-- Anyone can read active services
CREATE POLICY "Anyone can view active services" ON public.services
    FOR SELECT USING (status = 'Active');

-- Applications Policies
-- Citizens can view and insert their own applications
CREATE POLICY "Citizens can view their own applications" ON public.applications
    FOR SELECT USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Citizens can insert their own applications" ON public.applications
    FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id);
