#!/usr/bin/env node
// Generates the county reference seed (county row, sub-counties, wards) from the KNBS-derived
// `kenya-regions` dataset (MIT). Usage:
//   node scripts/gen-seed.mjs 47 [--data-dir path/to/kenya-regions/data] > seed.sql
//   node scripts/gen-seed.mjs 47 --json > src/shared/data/reference.nairobi.json   (bundled for offline use)
// Ward polygons are NOT part of this dataset; load them with scripts/load-boundaries.mjs.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const args = process.argv.slice(2);
const countyCode = Number(args.find((a) => /^\d+$/.test(a)));
const dirFlag = args.indexOf('--data-dir');
const dataDir = dirFlag >= 0 ? args[dirFlag + 1] : resolve('node_modules/kenya-regions/data');
if (!countyCode) {
  console.error('usage: gen-seed.mjs <county code> [--data-dir dir]');
  process.exit(1);
}

const load = (f) => JSON.parse(readFileSync(resolve(dataDir, f), 'utf8'));
const counties = load('counties.json');
const constituencies = load('constituencies.json');
const wards = load('wards.json');

const county = (Array.isArray(counties) ? counties : counties.counties).find((c) => c.code === countyCode);
if (!county) throw new Error(`county ${countyCode} not found`);
const cons = (Array.isArray(constituencies) ? constituencies : constituencies.constituencies).filter((c) => c.countyCode === countyCode);
const cw = wards.filter((w) => w.countyCode === countyCode);

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? 'null' : String(v));

// In Kenya's counties the administrative sub-county map onto constituencies closely enough for the
// public ward hierarchy; we key sub-counties by constituency (Nairobi: 17 of each).
const consByCode = new Map(cons.map((c) => [c.code, c]));

if (args.includes('--json')) {
  const r = (v) => (v === undefined ? null : v);
  console.log(
    JSON.stringify(
      {
        generatedBy: 'scripts/gen-seed.mjs',
        source: 'kenya-regions (KNBS/OCHA), MIT',
        county: {
          slug: county.slug,
          name: county.name,
          code: county.code,
          centroid: r(county.centroid),
          bbox: r(county.bbox),
          population2019: r(county.population?.['2019']),
        },
        subCounties: cons.map((c) => ({ id: c.slug, name: c.name, lat: r(c.centroid?.lat), lng: r(c.centroid?.lng), areaKm2: r(c.areaKm2) })),
        wards: cw.map((w) => ({ id: w.slug, code: w.code, name: w.name, subCountyId: consByCode.get(w.constituencyCode)?.slug ?? null })),
      },
      null,
      1,
    ),
  );
  process.exit(0);
}

const out = [];
out.push(`-- GENERATED by scripts/gen-seed.mjs for county ${countyCode} (${county.name}). Source: kenya-regions (KNBS/OCHA), MIT.`);
out.push(`insert into public.county (id, slug, name, code, centroid_lat, centroid_lng, bbox, default_locale)
values (1, ${q(county.slug)}, ${q(county.name)}, ${county.code}, ${n(county.centroid?.lat)}, ${n(county.centroid?.lng)}, ${county.bbox ? `array[${county.bbox.join(',')}]::numeric[]` : 'null'}, 'en')
on conflict (id) do update set slug = excluded.slug, name = excluded.name, code = excluded.code,
  centroid_lat = excluded.centroid_lat, centroid_lng = excluded.centroid_lng, bbox = excluded.bbox;`);

out.push('\ninsert into public.sub_counties (id, name, centroid_lat, centroid_lng, area_km2) values');
out.push(
  cons
    .map((c) => `  (${q(c.slug)}, ${q(c.name)}, ${n(c.centroid?.lat)}, ${n(c.centroid?.lng)}, ${n(c.areaKm2)})`)
    .join(',\n') + '\non conflict (id) do nothing;',
);

out.push('\ninsert into public.wards (id, code, name, sub_county_id, constituency) values');
out.push(
  cw
    .map((w) => {
      const c = consByCode.get(w.constituencyCode);
      return `  (${q(w.slug)}, ${w.code}, ${q(w.name)}, ${q(c?.slug)}, ${q(c?.name)})`;
    })
    .join(',\n') + '\non conflict (id) do nothing;',
);
console.log(out.join('\n'));
