-- Create tenders table
CREATE TABLE public.tenders (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    entity TEXT NOT NULL,
    value NUMERIC NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Open', 'Evaluated', 'Awarded', 'Cancelled')),
    deadline DATE NOT NULL,
    awarded_to TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create departments table
CREATE TABLE public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    head TEXT NOT NULL,
    staff INTEGER NOT NULL,
    services INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create notifications table
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('success', 'warning', 'info', 'error')),
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    read BOOLEAN DEFAULT FALSE NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Null if system-wide
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create revenue table
CREATE TABLE public.revenue (
    id TEXT PRIMARY KEY,
    ref TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    "user" TEXT NOT NULL,
    stream TEXT NOT NULL,
    time TEXT NOT NULL,
    reconciled BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create health_drugs table
CREATE TABLE public.health_drugs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    facility TEXT NOT NULL,
    stock TEXT NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('critical', 'low', 'high')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create welfare table
CREATE TABLE public.welfare (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Enrolled', 'Waitlist', 'Active', 'Inactive')),
    date TEXT NOT NULL,
    method TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create petitions table
CREATE TABLE public.petitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    deadline TEXT NOT NULL,
    supporters INTEGER NOT NULL DEFAULT 0,
    total_needed INTEGER NOT NULL,
    category TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create land_records table
CREATE TABLE public.land_records (
    id TEXT PRIMARY KEY,
    action TEXT NOT NULL,
    detail TEXT NOT NULL,
    status TEXT NOT NULL,
    hash TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create anomalies table
CREATE TABLE public.anomalies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('high', 'medium', 'low')),
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    dismissed BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.tenders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_drugs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.welfare ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.petitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.land_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anomalies ENABLE ROW LEVEL SECURITY;

-- Public / Citizens Policies
CREATE POLICY "Anyone can view open tenders" ON public.tenders FOR SELECT USING (true);
CREATE POLICY "Anyone can view departments" ON public.departments FOR SELECT USING (true);
CREATE POLICY "Users can view their notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Users can update their notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Anyone can view health drugs" ON public.health_drugs FOR SELECT USING (true);
CREATE POLICY "Anyone can view welfare programs" ON public.welfare FOR SELECT USING (true);
CREATE POLICY "Anyone can view petitions" ON public.petitions FOR SELECT USING (true);
CREATE POLICY "Anyone can vote on petitions" ON public.petitions FOR UPDATE USING (true);
CREATE POLICY "Anyone can view land records" ON public.land_records FOR SELECT USING (true);
